LIQUID_TICKERS = [
    "AAPL","MSFT","AMZN","GOOGL","GOOG","META","NVDA","TSLA","AVGO","ADBE",
    "CRM","INTU","CSCO","ORCL","AMD","QCOM","TXN","IBM","NOW","ADSK","SHOP",
    "JPM","BAC","WFC","C","GS","MS","BLK","SCHW","AXP","COF","BK","USB",
    "PNC","TFC","AIG","MET","PRU","TRV","ALL","CB","MMC","SPGI","MCO",
    "UNH","JNJ","PFE","MRK","ABBV","LLY","BMY","AMGN","GILD","REGN","VRTX",
    "PG","KO","PEP","WMT","COST","MDLZ","KHC","K","CL","CLX","EL","STZ",
    "HD","LOW","MCD","SBUX","NKE","TGT","DG","DLTR","ROST","TJX","MAR",
    "XOM","CVX","COP","EOG","PXD","SLB","HAL","BKR","MPC","PSX","VLO",
    "CAT","DE","BA","LMT","RTX","GD","NOC","HON","GE","ETN","EMR","ROK",
    "LIN","APD","SHW","ECL","PPG","ALB","NEM","FCX","MLM","VMC","NUE",
    "NEE","DUK","SO","D","AEP","EXC","SRE","XEL","ED","EIX","PEG","WEC",
    "PLD","AMT","CCI","EQIX","DLR","O","SPG","PSA","VTR","WELL","AVB",
    "DIS","NFLX","CMCSA","CHTR","T","VZ","TMUS","EA","TTWO","PARA","WBD",
    "GM","F","STLA","HOG","MNST","MO","INTC","MU","NXPI","LRCX","KLAC",
    "AMAT","MCHP","ON",
]
